### ETL Horno Eléctrico de Arco

#### Importamos librerías requeridas

In [1]:
import numpy as np
import pandas as pd

#### Importamos datos sin procesar

In [2]:
raw = pd.read_excel("../data/eaf.xlsx")
raw.head()

,start_date,stop_date,heat_id,steel_grade,num_buckets,total_scrap_t,bucket1_t,bucket2_t,bucket3_t,coque_kg,...,ladle_N2_stirr_Nm3,tap_lime_kg,tap_dolo_kg,tap_CaF2_kg,tap_Al_kg,tap_FeSi_kg,tap_FeSiMn_kg,tap_FeMn_kg,tap_SiC_kg,tap_carbon_kg
0,2023-01-09 09:44:10,2023-01-09 10:42:42,35019988,SAE 1011,3,95.200,43.000,32.000,20.2,150,...,0.0,411,94,104,0,92,724,0,0,0
1,2023-01-09 10:42:48,2023-01-09 11:48:42,35019989,SAE 1011,2,77.823,42.684,35.139,0.0,150,...,0.0,408,94,105,0,90,730,0,0,0
2,2023-01-09 11:48:46,2023-01-09 12:58:08,35019990,SAE 1011,2,81.024,45.486,35.538,0.0,150,...,0.0,408,95,103,0,90,724,0,0,0
3,2023-01-09 12:58:14,2023-01-09 13:55:24,35019991,SAE 1011,2,69.922,43.383,26.539,0.0,150,...,0.0,410,94,104,0,92,726,0,0,0
4,2023-01-09 13:55:28,2023-01-09 14:46:10,35019992,SAE 1011,2,80.993,45.393,35.600,0.0,0,...,0.9,409,95,105,0,92,730,0,0,0

In [3]:
raw.tail()

,start_date,stop_date,heat_id,steel_grade,num_buckets,total_scrap_t,bucket1_t,bucket2_t,bucket3_t,coque_kg,...,ladle_N2_stirr_Nm3,tap_lime_kg,tap_dolo_kg,tap_CaF2_kg,tap_Al_kg,tap_FeSi_kg,tap_FeSiMn_kg,tap_FeMn_kg,tap_SiC_kg,tap_carbon_kg
9932,2026-05-15 07:00:12,2026-05-15 07:47:50,35032284,SAE 1011,3,85.381,46.591,27.890,10.9,396,...,1.2,452,103,116,0,99,751,0,0,0
9933,2026-05-15 07:47:54,2026-05-15 08:42:20,35032285,SAE 1011,3,89.177,47.191,28.486,13.5,396,...,1.1,450,102,116,0,98,749,0,0,0
9934,2026-05-15 08:42:26,2026-05-15 09:26:32,35032286,SAE 1011,3,85.676,47.191,25.885,12.6,396,...,1.2,450,102,116,0,99,753,0,0,0
9935,2026-05-15 09:26:39,2026-05-15 10:10:18,35032287,SAE 1011,3,88.178,46.990,27.688,13.5,395,...,1.0,452,103,117,0,96,747,0,0,0
9936,2026-05-15 10:10:24,2026-05-15 10:53:12,35032288,SAE 1011,3,81.578,47.090,26.388,8.1,395,...,1.3,451,103,116,0,98,750,0,0,0

#### Forma del DataFrame y títulos de columnas

In [4]:
print("Forma del DataFrame: ", raw.shape)

Forma del DataFrame:  (9937, 50)

In [5]:
print("Índices del DataFrame: ", raw.index)

Índices del DataFrame:  RangeIndex(start=0, stop=9937, step=1)

Tenemos 10344 registros con 69 columnas

In [6]:
print("Títulos de columnas: \n\n", raw.columns)

Títulos de columnas:

 Index(['start_date', 'stop_date', 'heat_id', 'steel_grade', 'num_buckets',
       'total_scrap_t', 'bucket1_t', 'bucket2_t', 'bucket3_t', 'coque_kg',
       'lime_kg', 'dolo_kg', 'duration', 'p_on', 'p_off', 'avg_power_MW',
       'energy_MWh', 'energy_melt1_MWh', 'energy_melt2_MWh',
       'energy_melt3_MWh', 'energy_refining_MWh', 'oxygen_module_Nm3',
       'oxygen_total_Nm3', 'carbon_module_kg', 'fuel_module_Nm3',
       'fuel_total_Nm3', 'spec_energy_MWh/t', 'spec_oxygen_module_Nm3/t',
       'spec_carbon_module_kg/t', 'spec_fuel_Nm3/t', 'spec_coque_kg/t',
       'spec_lime_dolo_kg_t', 'final_temp_deg', 'final_oxygen_ppm',
       'end_hot_heel_t', 'tapped_weight_t', 'tapped_steel_t', 'tap_duration',
       'yield_%', 'ladle_Ar_stirr_Nm3', 'ladle_N2_stirr_Nm3', 'tap_lime_kg',
       'tap_dolo_kg', 'tap_CaF2_kg', 'tap_Al_kg', 'tap_FeSi_kg',
       'tap_FeSiMn_kg', 'tap_FeMn_kg', 'tap_SiC_kg', 'tap_carbon_kg'],
      dtype='str')

In [7]:
print("Tipo de dato por columna del DataFrame: \n\n", raw.dtypes)

Tipo de dato por columna del DataFrame:

 start_date                  datetime64[us]
stop_date                   datetime64[us]
heat_id                              int64
steel_grade                            str
num_buckets                          int64
total_scrap_t                      float64
bucket1_t                          float64
bucket2_t                          float64
bucket3_t                          float64
coque_kg                             int64
lime_kg                              int64
dolo_kg                              int64
duration                               str
p_on                                   str
p_off                                  str
avg_power_MW                       float64
energy_MWh                         float64
energy_melt1_MWh                   float64
energy_melt2_MWh                   float64
energy_melt3_MWh                   float64
energy_refining_MWh                float64
oxygen_module_Nm3                    int64
oxygen_total_Nm3                     int64
carbon_module_kg                     int64
fuel_module_Nm3                      int64
fuel_total_Nm3                       int64
spec_energy_MWh/t                  float64
spec_oxygen_module_Nm3/t           float64
spec_carbon_module_kg/t            float64
spec_fuel_Nm3/t                    float64
spec_coque_kg/t                    float64
spec_lime_dolo_kg_t                float64
final_temp_deg                       int64
final_oxygen_ppm                     int64
end_hot_heel_t                     float64
tapped_weight_t                    float64
tapped_steel_t                     float64
tap_duration                           str
yield_%                            float64
ladle_Ar_stirr_Nm3                 float64
ladle_N2_stirr_Nm3                 float64
tap_lime_kg                          int64
tap_dolo_kg                          int64
tap_CaF2_kg                          int64
tap_Al_kg                            int64
tap_FeSi_kg                          int64
tap_FeSiMn_kg                        int64
tap_FeMn_kg                          int64
tap_SiC_kg                           int64
tap_carbon_kg                        int64
dtype: object

#### Información básica de nuestro DataFrame:

In [8]:
raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 9937 entries, 0 to 9936
Data columns (total 50 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   start_date                9937 non-null   datetime64[us]
 1   stop_date                 9937 non-null   datetime64[us]
 2   heat_id                   9937 non-null   int64
 3   steel_grade               9937 non-null   str
 4   num_buckets               9937 non-null   int64
 5   total_scrap_t             9937 non-null   float64
 6   bucket1_t                 9937 non-null   float64
 7   bucket2_t                 9937 non-null   float64
 8   bucket3_t                 9937 non-null   float64
 9   coque_kg                  9937 non-null   int64
 10  lime_kg                   9937 non-null   int64
 11  dolo_kg                   9937 non-null   int64
 12  duration                  9937 non-null   str
 13  p_on                      9937 non-null   str
 14  p_off                     9937 non-null   str
 15  avg_power_MW              9937 non-null   float64
 16  energy_MWh                9937 non-null   float64
 17  energy_melt1_MWh          9937 non-null   float64
 18  energy_melt2_MWh          9937 non-null   float64
 19  energy_melt3_MWh          9937 non-null   float64
 20  energy_refining_MWh       9937 non-null   float64
 21  oxygen_module_Nm3         9937 non-null   int64
 22  oxygen_total_Nm3          9937 non-null   int64
 23  carbon_module_kg          9937 non-null   int64
 24  fuel_module_Nm3           9937 non-null   int64
 25  fuel_total_Nm3            9937 non-null   int64
 26  spec_energy_MWh/t         9937 non-null   float64
 27  spec_oxygen_module_Nm3/t  9937 non-null   float64
 28  spec_carbon_module_kg/t   9937 non-null   float64
 29  spec_fuel_Nm3/t           9937 non-null   float64
 30  spec_coque_kg/t           9937 non-null   float64
 31  spec_lime_dolo_kg_t       9937 non-null   float64
 32  final_temp_deg            9937 non-null   int64
 33  final_oxygen_ppm          9937 non-null   int64
 34  end_hot_heel_t            9937 non-null   float64
 35  tapped_weight_t           9937 non-null   float64
 36  tapped_steel_t            9937 non-null   float64
 37  tap_duration              9927 non-null   str
 38  yield_%                   9937 non-null   float64
 39  ladle_Ar_stirr_Nm3        9937 non-null   float64
 40  ladle_N2_stirr_Nm3        9937 non-null   float64
 41  tap_lime_kg               9937 non-null   int64
 42  tap_dolo_kg               9937 non-null   int64
 43  tap_CaF2_kg               9937 non-null   int64
 44  tap_Al_kg                 9937 non-null   int64
 45  tap_FeSi_kg               9937 non-null   int64
 46  tap_FeSiMn_kg             9937 non-null   int64
 47  tap_FeMn_kg               9937 non-null   int64
 48  tap_SiC_kg                9937 non-null   int64
 49  tap_carbon_kg             9937 non-null   int64
dtypes: datetime64[us](2), float64(22), int64(21), str(5)
memory usage: 3.8 MB

In [9]:
raw.isnull().sum()

start_date                   0
stop_date                    0
heat_id                      0
steel_grade                  0
num_buckets                  0
total_scrap_t                0
bucket1_t                    0
bucket2_t                    0
bucket3_t                    0
coque_kg                     0
lime_kg                      0
dolo_kg                      0
duration                     0
p_on                         0
p_off                        0
avg_power_MW                 0
energy_MWh                   0
energy_melt1_MWh             0
energy_melt2_MWh             0
energy_melt3_MWh             0
energy_refining_MWh          0
oxygen_module_Nm3            0
oxygen_total_Nm3             0
carbon_module_kg             0
fuel_module_Nm3              0
fuel_total_Nm3               0
spec_energy_MWh/t            0
spec_oxygen_module_Nm3/t     0
spec_carbon_module_kg/t      0
spec_fuel_Nm3/t              0
spec_coque_kg/t              0
spec_lime_dolo_kg_t          0
final_temp_deg               0
final_oxygen_ppm             0
end_hot_heel_t               0
tapped_weight_t              0
tapped_steel_t               0
tap_duration                10
yield_%                      0
ladle_Ar_stirr_Nm3           0
ladle_N2_stirr_Nm3           0
tap_lime_kg                  0
tap_dolo_kg                  0
tap_CaF2_kg                  0
tap_Al_kg                    0
tap_FeSi_kg                  0
tap_FeSiMn_kg                0
tap_FeMn_kg                  0
tap_SiC_kg                   0
tap_carbon_kg                0
dtype: int64

In [10]:
raw.duplicated().sum()

np.int64(0)

#### Tareas de limpieza a ejecutar:

- [ ] Corregir formato de fechas.
- [ ] Cambiar tipo de dato del número de colada a string.
- [ ] Verificar la distribución de grados de acero (gráfico de barras y torta).
- [ ] Cambiar tipo de dato de cantidad de cestas a entero.
- [ ] Dropear filas con peso nulo en cestas.
- [ ] Corregir tipo de dato en pesos total y de cesta 1.
- [ ] Corregir nulos en peso de cesta 3.
- [ ] Corregir nulos en peso de coque.

In [11]:
dropear = ['ladle_Ar_stirr_Nm3', 'ladle_N2_stirr_Nm3', 'tap_lime_kg',
       'tap_dolo_kg', 'tap_CaF2_kg', 'tap_Al_kg', 'tap_FeSi_kg',
       'tap_FeSiMn_kg', 'tap_FeMn_kg', 'tap_SiC_kg', 'tap_carbon_kg']

In [12]:
df = raw.copy()
df.drop(dropear, axis=1, inplace=True)
df.head()

,start_date,stop_date,heat_id,steel_grade,num_buckets,total_scrap_t,bucket1_t,bucket2_t,bucket3_t,coque_kg,...,spec_fuel_Nm3/t,spec_coque_kg/t,spec_lime_dolo_kg_t,final_temp_deg,final_oxygen_ppm,end_hot_heel_t,tapped_weight_t,tapped_steel_t,tap_duration,yield_%
0,2023-01-09 09:44:10,2023-01-09 10:42:42,35019988,SAE 1011,3,95.200,43.000,32.000,20.2,150,...,9.721060,2.092050,52.998605,1689,1376,0.0,71.7,70.275,01:34,73.818277
1,2023-01-09 10:42:48,2023-01-09 11:48:42,35019989,SAE 1011,2,77.823,42.684,35.139,0.0,150,...,5.416667,2.155172,56.422414,1672,1168,0.0,69.6,68.080,01:36,87.480565
2,2023-01-09 11:48:46,2023-01-09 12:58:08,35019990,SAE 1011,2,81.024,45.486,35.538,0.0,150,...,5.702128,2.127660,57.106383,1677,1029,0.0,70.5,68.987,01:34,85.143908
3,2023-01-09 12:58:14,2023-01-09 13:55:24,35019991,SAE 1011,2,69.922,43.383,26.539,0.0,150,...,4.871429,2.142857,56.114286,1676,945,0.0,70.0,68.481,01:36,97.939132
4,2023-01-09 13:55:28,2023-01-09 14:46:10,35019992,SAE 1011,2,80.993,45.393,35.600,0.0,0,...,5.470085,0.000000,35.712251,1681,718,0.0,70.2,68.676,01:30,84.792513