In [1]:
import pandas as pd

In [3]:
df_raw = pd.read_csv('../data/eaf.csv')
df_raw.head()

,start_date,stop_date,heat_id,steel_grade,buckets,total_scrap,bucket_1,bucket_2,bucket_3,coke,...,ladle_ar_stirr,ladle_n2_stirr,tapping_lime,tapping_dolo,tapping_caf2,tapping_fesi,tapping_fesimn,tapping_femn,tapping_sic,tapping_c
0,2024-01-01 23:35:48,2024-01-02 00:38:16,35024773,SAE 1011,3,100.390,47.500,32.500,20.39,500,...,0.0,1.0,340,152,75,92,675,0,0,0
1,2024-01-02 00:38:20,2024-01-02 01:44:44,35024774,SAE 1011,2,78.151,45.572,32.579,0.00,408,...,0.0,1.1,338,154,75,90,678,0,0,0
2,2024-01-02 01:44:48,2024-01-02 03:04:50,35024775,SAE 1011,2,77.854,45.776,32.078,0.00,405,...,0.0,1.1,339,153,75,98,680,0,0,0
3,2024-01-02 03:04:54,2024-01-02 03:56:56,35024776,SAE 1011,2,78.156,46.475,31.681,0.00,405,...,0.0,1.0,339,154,77,92,673,0,0,0
4,2024-01-02 03:57:02,2024-01-02 04:43:22,35024777,SAE 1011,2,77.257,46.076,31.181,0.00,405,...,0.0,1.1,339,154,77,91,684,0,0,0

In [4]:
df_raw.columns

Index(['start_date', 'stop_date', 'heat_id', 'steel_grade', 'buckets',
       'total_scrap', 'bucket_1', 'bucket_2', 'bucket_3', 'coke', 'lime',
       'dolo', 'duration', 'power_on', 'power_off', 'avg_power', 'energy',
       'energy_1', 'energy_2', 'energy_3', 'energy_refining', 'o2_module',
       'o2_total', 'c_module', 'fuel_module', 'fuel_total', 'spec_energy',
       'spec_o2_module', 'spec_c_module', 'spec_fuel', 'spec_coke',
       'spec_lime_dolo', 'final_temp', 'final_o2', 'end_hot_heel',
       'tapped_weight', 'tapped_steel', 'tap_duration', 'yield',
       'ladle_ar_stirr', 'ladle_n2_stirr', 'tapping_lime', 'tapping_dolo',
       'tapping_caf2', 'tapping_fesi', 'tapping_fesimn', 'tapping_femn',
       'tapping_sic', 'tapping_c'],
      dtype='object')

In [6]:
df_filtered = df_raw[['start_date', 'stop_date', 'heat_id', 'steel_grade', 'buckets',
       'total_scrap', 'bucket_1', 'bucket_2', 'bucket_3', 'coke', 'lime',
       'dolo', 'duration', 'power_on', 'power_off', 'avg_power', 'energy',
       'energy_1', 'energy_2', 'energy_3', 'energy_refining', 'o2_module',
       'o2_total', 'c_module', 'fuel_module', 'fuel_total', 'final_temp', 
       'final_o2', 'end_hot_heel', 'tapped_weight', 'tapped_steel', 'tap_duration']]
df_1022 = df_filtered[df_filtered['steel_grade'] == 'SAE 1022']
df_1022.head()

,start_date,stop_date,heat_id,steel_grade,buckets,total_scrap,bucket_1,bucket_2,bucket_3,coke,...,o2_total,c_module,fuel_module,fuel_total,final_temp,final_o2,end_hot_heel,tapped_weight,tapped_steel,tap_duration
95,2024-01-10 21:26:38,2024-01-10 22:27:38,35024890,SAE 1022,2,80.353,47.472,32.881,0.0,508,...,2589,452,351,675,1625,681,13.511,70.6,68.995,02:46
96,2024-01-11 00:54:34,2024-01-11 01:36:54,35024891,SAE 1022,2,78.957,47.474,31.483,0.0,506,...,2515,360,413,736,1663,934,12.897,69.8,68.203,02:56
97,2024-01-11 01:37:00,2024-01-11 02:23:44,35024892,SAE 1022,2,77.856,46.374,31.482,0.0,505,...,2459,433,338,646,1677,1014,11.817,69.8,68.192,03:00
98,2024-01-11 02:23:50,2024-01-11 03:30:18,35024893,SAE 1022,2,79.255,47.073,32.182,0.0,506,...,2411,522,341,627,1655,578,13.115,69.9,68.293,02:42
99,2024-01-11 03:30:22,2024-01-11 04:12:15,35024894,SAE 1022,2,79.052,47.372,31.680,0.0,507,...,2517,433,355,660,1622,492,12.617,70.2,68.591,02:40