### Práctica de ETL

#### 1. Importar librerías

In [1]:
import pandas as pd

#### 2. Extraer y visualizar datos

In [4]:
raw = pd.read_excel('/home/amolinasimancas/code/labs/gerdau/data/eaf_2025.xls')
raw.head()

,start_date,stop_date,heat_id,steel_grade,buckets,total_scrap_t,bucket_1_t,bucket_2_t,bucket_3_t,bucket_4_t,...,tapping_lime_kg,tapping_dolo_kg,tapping_cal_mezcla_kg,tapping_fluorita_kg,tapping_al_kg,tapping_fesi_kg,tapping_fesimn_kg,tapping_femn_kg,tapping_sic_kg,tapping_c_kg
0,2025-01-13 08:12:28,2025-01-13 10:19:22,35027408,SAE 1011,3,97.986,49.300,29.000,19.686,0,...,341,141,0,75,0,91,836,0,0,0
1,2025-01-13 10:19:26,2025-01-13 12:45:06,35027409,SAE 1011,3,89.872,49.786,30.486,9.600,0,...,338,151,0,74,0,94,674,0,0,0
2,2025-01-13 12:45:10,2025-01-13 13:50:02,35027410,SAE 1011,2,78.972,50.685,28.287,0.000,0,...,338,151,0,75,0,92,674,0,0,0
3,2025-01-13 22:43:34,2025-01-13 23:42:26,35027413,1523 MOD,3,98.660,50.086,28.988,19.586,0,...,338,151,0,85,0,30,39,0,0,0
4,2025-01-13 23:42:30,2025-01-14 01:43:42,35027414,1523 MOD,2,79.372,50.685,28.687,0.000,0,...,337,152,0,86,0,33,1107,0,139,0

#### 3. Listar columnas

In [9]:
raw.columns

Index(['start_date', 'stop_date', 'heat_id', 'steel_grade', 'buckets',
       'total_scrap_t', 'bucket_1_t', 'bucket_2_t', 'bucket_3_t', 'bucket_4_t',
       'coke_kg', 'lime_kg', 'dolo_kg', 'duration', 'p_on', 'p_off',
       'power_avg_mw', 'energy_total_mwh', 'energy_1_mwh', 'energy_2_mwh',
       'energy_3_mwh', 'energy_4_mwh', 'energy_ref_mwh', 'o2_module_nm3',
       'o2_total_nm3', 'c_module_kg', 'fuel_module_nm3', 'fuel_total_nm3',
       'energy_spec_kwh/t', 'o2_module_spec_nm3/t', 'c_module_espec_nm3/t',
       'fuel_espec_nm3', 'c_espec_kg/t', 'lime_dolo_espec_kg/t',
       'temp_final_cdeg', 'o2_final_ppm', 'end_hot_heel_t', 'tapped_weight_t',
       'tapped_steel_only_t', 'tap_duration', 'yield_%', 'furn_ar_stirr_nm3',
       'furn_n2_stirr_nm3', 'ladle_ar_stirr_nm3', 'ladle_n2_stirr_nm3',
       'tapping_lime_kg', 'tapping_dolo_kg', 'tapping_cal_mezcla_kg',
       'tapping_fluorita_kg', 'tapping_al_kg', 'tapping_fesi_kg',
       'tapping_fesimn_kg', 'tapping_femn_kg', 'tapping_sic_kg',
       'tapping_c_kg'],
      dtype='object')

#### 4. Ver información básica del dataframe

In [7]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1908 entries, 0 to 1907
Data columns (total 55 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   start_date             1908 non-null   datetime64[ns]
 1   stop_date              1908 non-null   datetime64[ns]
 2   heat_id                1908 non-null   int64
 3   steel_grade            1908 non-null   object
 4   buckets                1908 non-null   int64
 5   total_scrap_t          1908 non-null   float64
 6   bucket_1_t             1908 non-null   float64
 7   bucket_2_t             1908 non-null   float64
 8   bucket_3_t             1908 non-null   float64
 9   bucket_4_t             1908 non-null   int64
 10  coke_kg                1908 non-null   int64
 11  lime_kg                1908 non-null   int64
 12  dolo_kg                1908 non-null   int64
 13  duration               1908 non-null   object
 14  p_on                   1908 non-null   object
 15  p_off                  1908 non-null   object
 16  power_avg_mw           1908 non-null   float64
 17  energy_total_mwh       1908 non-null   float64
 18  energy_1_mwh           1908 non-null   float64
 19  energy_2_mwh           1908 non-null   float64
 20  energy_3_mwh           1908 non-null   float64
 21  energy_4_mwh           1908 non-null   int64
 22  energy_ref_mwh         1908 non-null   float64
 23  o2_module_nm3          1908 non-null   int64
 24  o2_total_nm3           1908 non-null   int64
 25  c_module_kg            1908 non-null   int64
 26  fuel_module_nm3        1908 non-null   int64
 27  fuel_total_nm3         1908 non-null   int64
 28  energy_spec_kwh/t      1908 non-null   float64
 29  o2_module_spec_nm3/t   1908 non-null   float64
 30  c_module_espec_nm3/t   1908 non-null   float64
 31  fuel_espec_nm3         1908 non-null   float64
 32  c_espec_kg/t           1908 non-null   float64
 33  lime_dolo_espec_kg/t   1908 non-null   float64
 34  temp_final_cdeg        1908 non-null   int64
 35  o2_final_ppm           1908 non-null   int64
 36  end_hot_heel_t         1908 non-null   float64
 37  tapped_weight_t        1908 non-null   float64
 38  tapped_steel_only_t    1908 non-null   float64
 39  tap_duration           1908 non-null   object
 40  yield_%                1908 non-null   float64
 41  furn_ar_stirr_nm3      1908 non-null   int64
 42  furn_n2_stirr_nm3      1908 non-null   int64
 43  ladle_ar_stirr_nm3     1908 non-null   float64
 44  ladle_n2_stirr_nm3     1908 non-null   float64
 45  tapping_lime_kg        1908 non-null   int64
 46  tapping_dolo_kg        1908 non-null   int64
 47  tapping_cal_mezcla_kg  1908 non-null   int64
 48  tapping_fluorita_kg    1908 non-null   int64
 49  tapping_al_kg          1908 non-null   int64
 50  tapping_fesi_kg        1908 non-null   int64
 51  tapping_fesimn_kg      1908 non-null   int64
 52  tapping_femn_kg        1908 non-null   int64
 53  tapping_sic_kg         1908 non-null   int64
 54  tapping_c_kg           1908 non-null   int64
dtypes: datetime64[ns](2), float64(22), int64(26), object(5)
memory usage: 820.0+ KB

#### 5. Ver estadísticos descriptivos por columnas

In [10]:
raw.describe()

,start_date,stop_date,heat_id,buckets,total_scrap_t,bucket_1_t,bucket_2_t,bucket_3_t,bucket_4_t,coke_kg,...,tapping_lime_kg,tapping_dolo_kg,tapping_cal_mezcla_kg,tapping_fluorita_kg,tapping_al_kg,tapping_fesi_kg,tapping_fesimn_kg,tapping_femn_kg,tapping_sic_kg,tapping_c_kg
count,1908,1908,1.908000e+03,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000,1908.0,1908.000000,...,1908.000000,1908.000000,1908.0,1908.000000,1908.0,1908.000000,1908.000000,1908.000000,1908.000000,1908.000000
mean,2025-05-14 17:07:00.600628992,2025-05-14 18:09:08.740566016,3.502862e+07,2.539832,84.116977,48.556939,28.213504,7.346534,0.0,358.445493,...,374.898847,150.476939,0.0,104.572327,0.0,38.802411,957.496331,7.269392,53.903040,73.403040
min,2025-01-13 08:12:28,2025-01-13 10:19:22,3.502741e+07,2.000000,60.920000,39.284000,14.787000,0.000000,0.0,0.000000,...,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2025-03-05 06:03:36.500000,2025-03-05 07:08:54.500000,3.502801e+07,2.000000,80.699000,45.949500,26.188750,0.000000,0.0,305.000000,...,340.000000,151.000000,0.0,87.000000,0.0,0.000000,805.000000,0.000000,0.000000,51.000000
50%,2025-04-29 12:05:39,2025-04-29 13:07:59,3.502865e+07,3.000000,84.072000,48.440000,27.687500,10.200000,0.0,405.000000,...,397.000000,152.000000,0.0,116.000000,0.0,27.500000,857.000000,0.000000,69.000000,72.000000
75%,2025-08-08 10:57:07,2025-08-08 11:47:19,3.502922e+07,3.000000,86.241000,50.882000,29.776000,13.300000,0.0,496.000000,...,400.000000,153.000000,0.0,120.000000,0.0,63.000000,1215.500000,0.000000,83.250000,131.000000
max,2025-09-26 12:59:38,2025-09-26 13:45:56,3.502984e+07,3.000000,104.877000,62.800000,40.386000,21.000000,0.0,812.000000,...,717.000000,389.000000,0.0,173.000000,0.0,243.000000,3198.000000,433.000000,410.000000,326.000000
std,NaN,NaN,6.981850e+02,0.498542,4.627106,2.931579,2.691233,7.062659,0.0,162.389762,...,40.335181,23.266541,0.0,18.736953,0.0,44.444768,277.467188,53.327679,53.485464,55.044641

#### 6. Métricas de calidad y perfilado de datos

**Completitud**

In [13]:
raw.isnull()

,start_date,stop_date,heat_id,steel_grade,buckets,total_scrap_t,bucket_1_t,bucket_2_t,bucket_3_t,bucket_4_t,...,tapping_lime_kg,tapping_dolo_kg,tapping_cal_mezcla_kg,tapping_fluorita_kg,tapping_al_kg,tapping_fesi_kg,tapping_fesimn_kg,tapping_femn_kg,tapping_sic_kg,tapping_c_kg
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1904,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1905,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1906,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1907,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
raw.isnull().sum()

start_date               0
stop_date                0
heat_id                  0
steel_grade              0
buckets                  0
total_scrap_t            0
bucket_1_t               0
bucket_2_t               0
bucket_3_t               0
bucket_4_t               0
coke_kg                  0
lime_kg                  0
dolo_kg                  0
duration                 0
p_on                     0
p_off                    0
power_avg_mw             0
energy_total_mwh         0
energy_1_mwh             0
energy_2_mwh             0
energy_3_mwh             0
energy_4_mwh             0
energy_ref_mwh           0
o2_module_nm3            0
o2_total_nm3             0
c_module_kg              0
fuel_module_nm3          0
fuel_total_nm3           0
energy_spec_kwh/t        0
o2_module_spec_nm3/t     0
c_module_espec_nm3/t     0
fuel_espec_nm3           0
c_espec_kg/t             0
lime_dolo_espec_kg/t     0
temp_final_cdeg          0
o2_final_ppm             0
end_hot_heel_t           0
tapped_weight_t          0
tapped_steel_only_t      0
tap_duration             0
yield_%                  0
furn_ar_stirr_nm3        0
furn_n2_stirr_nm3        0
ladle_ar_stirr_nm3       0
ladle_n2_stirr_nm3       0
tapping_lime_kg          0
tapping_dolo_kg          0
tapping_cal_mezcla_kg    0
tapping_fluorita_kg      0
tapping_al_kg            0
tapping_fesi_kg          0
tapping_fesimn_kg        0
tapping_femn_kg          0
tapping_sic_kg           0
tapping_c_kg             0
dtype: int64

**Unicidad**

In [12]:
duplicates = raw.duplicated()
duplicates.sum()

np.int64(0)

#### 7. Limpieza

In [14]:
dropeados = raw.dropna()

In [ ]:
# rellenados = raw.fillna({'numerico':0, 'texto':'desconocido'})